### ISSUE TITLE
APK стал весить на 6 мб больше

### ISSUE THREAD

**Issue by Snowmaze-dev** [VKCOM/KNet#2]
Раньше пробовал Cronet отдельно и размер apk рос буквально на 200 кб, сейчас размер apk растёт с 2 мб до 8 мб. В частности из-за либ Cronet, которые 12мб в распакованном состоянии весят. Так и должно быть?
![image](https://user-images.githubusercontent.com/33610714/135780831-181b065c-b91c-4fff-9765-5685206738b0.png)

**Comment by Snowmaze-dev** [comment]
Вижу они в knet/cronet/src/main/jniLibs лежат, но они серьёзно так нужны?

**Comment by anchupin** [comment]
Добрый день, APK действительно становится больше, в основном, за счет динамических библиотек.

Для Release APK это.
ArchivePathEntry: pathPrefix="", path="/lib/x86/libcronet.93.0.4577.82.so" - 2MB
ArchivePathEntry: pathPrefix="", path="/lib/arm64-v8a/libcronet.93.0.4577.82.so" - 2MB
ArchivePathEntry: pathPrefix="", path="/lib/armeabi-v7a/libcronet.93.0.4577.82.so" - 1.9 MB

Они нужны, т.к. в них находится вся логика работы с quic и другими network протоколами, в данный момент мы работаем над тем, чтобы они стали меньше.

**Что можно сделать?**
**Debug:**
Размер APK не должен вам мешать при разработке, а так же не должен увеличивать время вашей компиляции, т.к. все gradle задачи, связанные с нативными библиотеками занимают достаточно мало времени, а так же кешируются(если у вас включен build cache).
Или вы можете сделать flavour для разных типов процессоров:
``` Kotlin
// Kotlin Gradle DSL
flavorDimensions += listOf("abi")
productFlavors {
    setup("arm") {
        dimension = "abi"
        ndk {
            abiFilters += setOf("armeabi-v7a", "arm64-v8a")
        }
    }
    setup("x86") {
        dimension = "abi"
        ndk {
            abiFilters +=setOf("x86")
        }
    }
}
```   

**Release:**
Вы можете использовать ABB, вместе APK, для публикации в Google Play, тогда размер APK будет увеличен только на 2 MB, т.к. для конкретного телефона нужна только одна версия библиотеки(arm7 arm8 или x86) в зависимости от типа CPU.
