### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by Snowmaze-dev** [VKCOM/KNet#3]
Какие rules надо для proguard? С proguard получаю ошибку java.lang.RuntimeException: Unable to find any Cronet provider. Have you included all necessary jars?
Пробовал
```
-keep class org.chromium.net.impl.NativeCronetProvider {
    public <init>(android.content.Context);
}
```
С таким правилом получаю java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/apppackage/lib/arm64/libcronet.93.0.4577.82.so"

**Comment by anchupin** [comment]
Можешь попробовать взять тут
[cronet_impl_native_proguard.txt](https://github.com/VKCOM/KNet/files/7278839/cronet_impl_native_proguard.txt)


Но если у тебя "UnsatisfiedLinkError", то скорее он не может найти сам so файл

В ближайшее вермя добавлю прогвард файл в либу + добавлю семпл

**Comment by Snowmaze-dev** [comment]
Добавил правила, теперь работает) Странно, что размер APK не изменился, наверное, proguard какие-то имена обсфусцировал и поэтому ошибка

**Comment by anchupin** [comment]
"Странно, что размер APK не изменился, наверное, proguard какие-то имена обсфусцировал и поэтому ошибка"
Можешь немного поподробнее?)

**Comment by Snowmaze-dev** [comment]
Ну такая логика, что если бы proguard удалял бы провайдер, то размер APK был бы наверное сильно меньше, но он тот же остался почти, значит просто какое-то название обсфусцировал и какой-то небольшой класс удалил.
С правилами вес APK 8,575кб, а без правил 8, 504кб

**Comment by anchupin** [comment]
Тут все верно, данный прогвард просто в keep сохраняет несколько java файлов, от этого размер сильно меньше не станет.

**Comment by anchupin** [comment]
Опять же, единственный хороший способ уменьшить размер APK, просто собирать ABB файлы.

**Comment by Snowmaze-dev** [comment]
Ну, моего приложения пока в плеймаркете нет, просто с proguard между друзей распространял версию)

**Comment by anchupin** [comment]
А, ясно, тогда пока только так, к сожалению. Ты можешь вырезать x86 архитектуру, врят ли они будут смотреть его на эмуляторе, как это можно сделать через flavour я писал в предыдущем issue.
Так же можешь просто указать в `android {` в build.gradle файле
```
// Kotlin Gradle DSL
ndk {
     abiFilters += setOf("armeabi-v7a", "arm64-v8a")
}
```

Это поможет вырезать 2 МБ

**Comment by Snowmaze-dev** [comment]
Угу, спасибо
`ndk {
 abiFilters 'armeabi-v7a', 'arm64-v8a'
}`
на груви если кому-то надо будет)
